# Generated by Django 4.1.13 on 2024-09-29 07:44

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0003_remove_city_city_city_cites'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasUsage',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField(default=100)),
                ('is_gas_leak', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gas_usage',
            },
        ),
    ]
